# Generated by Django 4.0.1 on 2022-01-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factorialapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactorialofNumber',
            new_name='FactorialNumber',
        ),
    ]
