# Generated by Django 4.0.1 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factorialapi', '0002_rename_factorialofnumber_factorialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorialnumber',
            name='number',
            field=models.IntegerField(),
        ),
    ]
